/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductProductIdRouteImport } from './routes/product.$productId'
import { Route as AuthenticatedCheckoutRouteImport } from './routes/_authenticated/checkout'
import { Route as AuthenticatedAdmin_spaceRouteImport } from './routes/_authenticated/_admin_space'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthenticatedPaymentSuccessRouteImport } from './routes/_authenticated/payment/success'
import { Route as AuthenticatedPaymentCancelRouteImport } from './routes/_authenticated/payment/cancel'
import { Route as AuthenticatedAccountProfileRouteImport } from './routes/_authenticated/account/profile'
import { Route as AuthenticatedAdmin_spaceAdminUserListRouteImport } from './routes/_authenticated/_admin_space/admin/user-list'
import { Route as AuthenticatedAdmin_spaceAdminProductNewRouteImport } from './routes/_authenticated/_admin_space/admin/product-new'
import { Route as AuthenticatedAdmin_spaceAdminProductListRouteImport } from './routes/_authenticated/_admin_space/admin/product-list'
import { Route as AuthenticatedAdmin_spaceAdminOrderListRouteImport } from './routes/_authenticated/_admin_space/admin/order-list'
import { Route as AuthenticatedAdmin_spaceAdminDashboardRouteImport } from './routes/_authenticated/_admin_space/admin/dashboard'
import { Route as AuthenticatedAdmin_spaceAdminCategoryNewRouteImport } from './routes/_authenticated/_admin_space/admin/category-new'
import { Route as AuthenticatedAdmin_spaceAdminCategoryListRouteImport } from './routes/_authenticated/_admin_space/admin/category-list'

const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductProductIdRoute = ProductProductIdRouteImport.update({
  id: '/product/$productId',
  path: '/product/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCheckoutRoute = AuthenticatedCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdmin_spaceRoute =
  AuthenticatedAdmin_spaceRouteImport.update({
    id: '/_admin_space',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedPaymentSuccessRoute =
  AuthenticatedPaymentSuccessRouteImport.update({
    id: '/payment/success',
    path: '/payment/success',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPaymentCancelRoute =
  AuthenticatedPaymentCancelRouteImport.update({
    id: '/payment/cancel',
    path: '/payment/cancel',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAccountProfileRoute =
  AuthenticatedAccountProfileRouteImport.update({
    id: '/account/profile',
    path: '/account/profile',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdmin_spaceAdminUserListRoute =
  AuthenticatedAdmin_spaceAdminUserListRouteImport.update({
    id: '/admin/user-list',
    path: '/admin/user-list',
    getParentRoute: () => AuthenticatedAdmin_spaceRoute,
  } as any)
const AuthenticatedAdmin_spaceAdminProductNewRoute =
  AuthenticatedAdmin_spaceAdminProductNewRouteImport.update({
    id: '/admin/product-new',
    path: '/admin/product-new',
    getParentRoute: () => AuthenticatedAdmin_spaceRoute,
  } as any)
const AuthenticatedAdmin_spaceAdminProductListRoute =
  AuthenticatedAdmin_spaceAdminProductListRouteImport.update({
    id: '/admin/product-list',
    path: '/admin/product-list',
    getParentRoute: () => AuthenticatedAdmin_spaceRoute,
  } as any)
const AuthenticatedAdmin_spaceAdminOrderListRoute =
  AuthenticatedAdmin_spaceAdminOrderListRouteImport.update({
    id: '/admin/order-list',
    path: '/admin/order-list',
    getParentRoute: () => AuthenticatedAdmin_spaceRoute,
  } as any)
const AuthenticatedAdmin_spaceAdminDashboardRoute =
  AuthenticatedAdmin_spaceAdminDashboardRouteImport.update({
    id: '/admin/dashboard',
    path: '/admin/dashboard',
    getParentRoute: () => AuthenticatedAdmin_spaceRoute,
  } as any)
const AuthenticatedAdmin_spaceAdminCategoryNewRoute =
  AuthenticatedAdmin_spaceAdminCategoryNewRouteImport.update({
    id: '/admin/category-new',
    path: '/admin/category-new',
    getParentRoute: () => AuthenticatedAdmin_spaceRoute,
  } as any)
const AuthenticatedAdmin_spaceAdminCategoryListRoute =
  AuthenticatedAdmin_spaceAdminCategoryListRouteImport.update({
    id: '/admin/category-list',
    path: '/admin/category-list',
    getParentRoute: () => AuthenticatedAdmin_spaceRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/account/profile': typeof AuthenticatedAccountProfileRoute
  '/payment/cancel': typeof AuthenticatedPaymentCancelRoute
  '/payment/success': typeof AuthenticatedPaymentSuccessRoute
  '/admin/category-list': typeof AuthenticatedAdmin_spaceAdminCategoryListRoute
  '/admin/category-new': typeof AuthenticatedAdmin_spaceAdminCategoryNewRoute
  '/admin/dashboard': typeof AuthenticatedAdmin_spaceAdminDashboardRoute
  '/admin/order-list': typeof AuthenticatedAdmin_spaceAdminOrderListRoute
  '/admin/product-list': typeof AuthenticatedAdmin_spaceAdminProductListRoute
  '/admin/product-new': typeof AuthenticatedAdmin_spaceAdminProductNewRoute
  '/admin/user-list': typeof AuthenticatedAdmin_spaceAdminUserListRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/account/profile': typeof AuthenticatedAccountProfileRoute
  '/payment/cancel': typeof AuthenticatedPaymentCancelRoute
  '/payment/success': typeof AuthenticatedPaymentSuccessRoute
  '/admin/category-list': typeof AuthenticatedAdmin_spaceAdminCategoryListRoute
  '/admin/category-new': typeof AuthenticatedAdmin_spaceAdminCategoryNewRoute
  '/admin/dashboard': typeof AuthenticatedAdmin_spaceAdminDashboardRoute
  '/admin/order-list': typeof AuthenticatedAdmin_spaceAdminOrderListRoute
  '/admin/product-list': typeof AuthenticatedAdmin_spaceAdminProductListRoute
  '/admin/product-new': typeof AuthenticatedAdmin_spaceAdminProductNewRoute
  '/admin/user-list': typeof AuthenticatedAdmin_spaceAdminUserListRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_authenticated/_admin_space': typeof AuthenticatedAdmin_spaceRouteWithChildren
  '/_authenticated/checkout': typeof AuthenticatedCheckoutRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/_authenticated/account/profile': typeof AuthenticatedAccountProfileRoute
  '/_authenticated/payment/cancel': typeof AuthenticatedPaymentCancelRoute
  '/_authenticated/payment/success': typeof AuthenticatedPaymentSuccessRoute
  '/_authenticated/_admin_space/admin/category-list': typeof AuthenticatedAdmin_spaceAdminCategoryListRoute
  '/_authenticated/_admin_space/admin/category-new': typeof AuthenticatedAdmin_spaceAdminCategoryNewRoute
  '/_authenticated/_admin_space/admin/dashboard': typeof AuthenticatedAdmin_spaceAdminDashboardRoute
  '/_authenticated/_admin_space/admin/order-list': typeof AuthenticatedAdmin_spaceAdminOrderListRoute
  '/_authenticated/_admin_space/admin/product-list': typeof AuthenticatedAdmin_spaceAdminProductListRoute
  '/_authenticated/_admin_space/admin/product-new': typeof AuthenticatedAdmin_spaceAdminProductNewRoute
  '/_authenticated/_admin_space/admin/user-list': typeof AuthenticatedAdmin_spaceAdminUserListRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/login'
    | '/register'
    | '/checkout'
    | '/product/$productId'
    | '/account/profile'
    | '/payment/cancel'
    | '/payment/success'
    | '/admin/category-list'
    | '/admin/category-new'
    | '/admin/dashboard'
    | '/admin/order-list'
    | '/admin/product-list'
    | '/admin/product-new'
    | '/admin/user-list'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/login'
    | '/register'
    | '/checkout'
    | '/product/$productId'
    | '/account/profile'
    | '/payment/cancel'
    | '/payment/success'
    | '/admin/category-list'
    | '/admin/category-new'
    | '/admin/dashboard'
    | '/admin/order-list'
    | '/admin/product-list'
    | '/admin/product-new'
    | '/admin/user-list'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_authenticated'
    | '/about'
    | '/contact'
    | '/_auth/login'
    | '/_auth/register'
    | '/_authenticated/_admin_space'
    | '/_authenticated/checkout'
    | '/product/$productId'
    | '/_authenticated/account/profile'
    | '/_authenticated/payment/cancel'
    | '/_authenticated/payment/success'
    | '/_authenticated/_admin_space/admin/category-list'
    | '/_authenticated/_admin_space/admin/category-new'
    | '/_authenticated/_admin_space/admin/dashboard'
    | '/_authenticated/_admin_space/admin/order-list'
    | '/_authenticated/_admin_space/admin/product-list'
    | '/_authenticated/_admin_space/admin/product-new'
    | '/_authenticated/_admin_space/admin/user-list'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ProductProductIdRoute: typeof ProductProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$productId': {
      id: '/product/$productId'
      path: '/product/$productId'
      fullPath: '/product/$productId'
      preLoaderRoute: typeof ProductProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/checkout': {
      id: '/_authenticated/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof AuthenticatedCheckoutRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_admin_space': {
      id: '/_authenticated/_admin_space'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdmin_spaceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/payment/success': {
      id: '/_authenticated/payment/success'
      path: '/payment/success'
      fullPath: '/payment/success'
      preLoaderRoute: typeof AuthenticatedPaymentSuccessRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/payment/cancel': {
      id: '/_authenticated/payment/cancel'
      path: '/payment/cancel'
      fullPath: '/payment/cancel'
      preLoaderRoute: typeof AuthenticatedPaymentCancelRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/account/profile': {
      id: '/_authenticated/account/profile'
      path: '/account/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AuthenticatedAccountProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/_admin_space/admin/user-list': {
      id: '/_authenticated/_admin_space/admin/user-list'
      path: '/admin/user-list'
      fullPath: '/admin/user-list'
      preLoaderRoute: typeof AuthenticatedAdmin_spaceAdminUserListRouteImport
      parentRoute: typeof AuthenticatedAdmin_spaceRoute
    }
    '/_authenticated/_admin_space/admin/product-new': {
      id: '/_authenticated/_admin_space/admin/product-new'
      path: '/admin/product-new'
      fullPath: '/admin/product-new'
      preLoaderRoute: typeof AuthenticatedAdmin_spaceAdminProductNewRouteImport
      parentRoute: typeof AuthenticatedAdmin_spaceRoute
    }
    '/_authenticated/_admin_space/admin/product-list': {
      id: '/_authenticated/_admin_space/admin/product-list'
      path: '/admin/product-list'
      fullPath: '/admin/product-list'
      preLoaderRoute: typeof AuthenticatedAdmin_spaceAdminProductListRouteImport
      parentRoute: typeof AuthenticatedAdmin_spaceRoute
    }
    '/_authenticated/_admin_space/admin/order-list': {
      id: '/_authenticated/_admin_space/admin/order-list'
      path: '/admin/order-list'
      fullPath: '/admin/order-list'
      preLoaderRoute: typeof AuthenticatedAdmin_spaceAdminOrderListRouteImport
      parentRoute: typeof AuthenticatedAdmin_spaceRoute
    }
    '/_authenticated/_admin_space/admin/dashboard': {
      id: '/_authenticated/_admin_space/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdmin_spaceAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedAdmin_spaceRoute
    }
    '/_authenticated/_admin_space/admin/category-new': {
      id: '/_authenticated/_admin_space/admin/category-new'
      path: '/admin/category-new'
      fullPath: '/admin/category-new'
      preLoaderRoute: typeof AuthenticatedAdmin_spaceAdminCategoryNewRouteImport
      parentRoute: typeof AuthenticatedAdmin_spaceRoute
    }
    '/_authenticated/_admin_space/admin/category-list': {
      id: '/_authenticated/_admin_space/admin/category-list'
      path: '/admin/category-list'
      fullPath: '/admin/category-list'
      preLoaderRoute: typeof AuthenticatedAdmin_spaceAdminCategoryListRouteImport
      parentRoute: typeof AuthenticatedAdmin_spaceRoute
    }
  }
}

interface AuthRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AuthenticatedAdmin_spaceRouteChildren {
  AuthenticatedAdmin_spaceAdminCategoryListRoute: typeof AuthenticatedAdmin_spaceAdminCategoryListRoute
  AuthenticatedAdmin_spaceAdminCategoryNewRoute: typeof AuthenticatedAdmin_spaceAdminCategoryNewRoute
  AuthenticatedAdmin_spaceAdminDashboardRoute: typeof AuthenticatedAdmin_spaceAdminDashboardRoute
  AuthenticatedAdmin_spaceAdminOrderListRoute: typeof AuthenticatedAdmin_spaceAdminOrderListRoute
  AuthenticatedAdmin_spaceAdminProductListRoute: typeof AuthenticatedAdmin_spaceAdminProductListRoute
  AuthenticatedAdmin_spaceAdminProductNewRoute: typeof AuthenticatedAdmin_spaceAdminProductNewRoute
  AuthenticatedAdmin_spaceAdminUserListRoute: typeof AuthenticatedAdmin_spaceAdminUserListRoute
}

const AuthenticatedAdmin_spaceRouteChildren: AuthenticatedAdmin_spaceRouteChildren =
  {
    AuthenticatedAdmin_spaceAdminCategoryListRoute:
      AuthenticatedAdmin_spaceAdminCategoryListRoute,
    AuthenticatedAdmin_spaceAdminCategoryNewRoute:
      AuthenticatedAdmin_spaceAdminCategoryNewRoute,
    AuthenticatedAdmin_spaceAdminDashboardRoute:
      AuthenticatedAdmin_spaceAdminDashboardRoute,
    AuthenticatedAdmin_spaceAdminOrderListRoute:
      AuthenticatedAdmin_spaceAdminOrderListRoute,
    AuthenticatedAdmin_spaceAdminProductListRoute:
      AuthenticatedAdmin_spaceAdminProductListRoute,
    AuthenticatedAdmin_spaceAdminProductNewRoute:
      AuthenticatedAdmin_spaceAdminProductNewRoute,
    AuthenticatedAdmin_spaceAdminUserListRoute:
      AuthenticatedAdmin_spaceAdminUserListRoute,
  }

const AuthenticatedAdmin_spaceRouteWithChildren =
  AuthenticatedAdmin_spaceRoute._addFileChildren(
    AuthenticatedAdmin_spaceRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedAdmin_spaceRoute: typeof AuthenticatedAdmin_spaceRouteWithChildren
  AuthenticatedCheckoutRoute: typeof AuthenticatedCheckoutRoute
  AuthenticatedAccountProfileRoute: typeof AuthenticatedAccountProfileRoute
  AuthenticatedPaymentCancelRoute: typeof AuthenticatedPaymentCancelRoute
  AuthenticatedPaymentSuccessRoute: typeof AuthenticatedPaymentSuccessRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdmin_spaceRoute: AuthenticatedAdmin_spaceRouteWithChildren,
  AuthenticatedCheckoutRoute: AuthenticatedCheckoutRoute,
  AuthenticatedAccountProfileRoute: AuthenticatedAccountProfileRoute,
  AuthenticatedPaymentCancelRoute: AuthenticatedPaymentCancelRoute,
  AuthenticatedPaymentSuccessRoute: AuthenticatedPaymentSuccessRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ProductProductIdRoute: ProductProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
