"""image link for product

Revision ID: 0b54f9a0c0e7
Revises: ded52b2fc04b
Create Date: 2026-05-05 21:04:23.285270

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b54f9a0c0e7'
down_revision: Union[str, Sequence[str], None] = 'ded52b2fc04b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('image_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'image_link')
    # ### end Alembic commands ###
