"""cart status column and delete total_price

Revision ID: 92ef1a8e64f8
Revises: 0b54f9a0c0e7
Create Date: 2026-05-31 21:20:33.693028

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92ef1a8e64f8'
down_revision: Union[str, Sequence[str], None] = '0b54f9a0c0e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('status', sa.String(), nullable=True))
    op.drop_column('carts', 'total_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('carts', sa.Column('total_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('carts', 'status')
    # ### end Alembic commands ###
